### ISSUE TITLE
Finalize sprites for rhythm game

### ISSUE THREAD

**Issue by yasminadaniel** [TheHermanator77/Interactive-Comic#5]
Finalize the sprites for the rhythm game. Put that in the scene

**Comment by wmullani** [comment]
Static sprites of the villain (Dr. Heisenberg) and the protagonist (Bella) designed for use in the rhythm game. (Bella has a fully opaque and a semi transparent sprite, to represent the probability where she is observed and the other probabilities in which she could have been observed respectively). Also, four differently colored energy bullets for the villain to shoot at the player have been designed.
